#!/usr/bin/env bash
# commnds to install nginx in web server

sudo apt update
sudo apt install -y nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t

sudo service nginx reload