#!/usr/bin/env bash
# connects to the file

# Set the SSH private key file
PRIVATE_KEY=~/.ssh/school

# Set the username
USERNAME=ubuntu

# Set the hostname or IP address of the server
HOST=8.8.8.8

# Connect to the server using SSH
ssh -i "$PRIVATE_KEY" "$USERNAME"@"$HOST"

